"""update user schema to include enabled/disabled state

Revision ID: e5c906302540
Revises: 6145ecc436ea
Create Date: 2026-01-03 00:01:37.946925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c906302540'
down_revision: Union[str, Sequence[str], None] = '6145ecc436ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('firstname', sa.String(length=15), nullable=False))
    op.add_column('user_account', sa.Column('lastname', sa.String(length=20), nullable=False))
    op.add_column('user_account', sa.Column('is_enabled', sa.Boolean(), nullable=False))
    op.drop_column('user_account', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('name', sa.VARCHAR(length=30), nullable=False))
    op.drop_column('user_account', 'is_enabled')
    op.drop_column('user_account', 'lastname')
    op.drop_column('user_account', 'firstname')
    # ### end Alembic commands ###
